version: "3.9"
services:
  jfgr-authentication-ecommerce-api:
    restart: always
    build: 
      context: ./../../../projects/autenticacao
      dockerfile: Dockerfile
    ports:
      - "${AUTH_API_PORT}:8080"
    networks:
      - jfgr-ecommerce
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AUTH_DB=${AUTH_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_API_PORT=8080
      - TZ=America/Sao_Paulo
  jfgr-authentication-ecommerce-postgresql:
    restart: always
    build:
      context: .
      dockerfile: postgresql.dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${AUTH_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=${POSTGRES_PORT}
    volumes:
      - jfgr-authentication-ecommerce-pgdata:/var/lib/postgresql/data
    networks:
      - jfgr-ecommerce
networks:
  jfgr-ecommerce:
    external: true
volumes: 
  jfgr-authentication-ecommerce-pgdata: