version: "3.9"
services:
  jfgr-gateway-ecommerce-api:
    restart: always
    build: 
      context: ./../../../projects/gateway
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    networks:
      - jfgr-ecommerce
    environment:
      - AUTH_API_HOST=http://jfgr-authentication-ecommerce-api
      - AUTH_API_PORT=8080
      - GESTAO_ITENS_API_HOST=http://jfgr-gestao-itens-ecommerce-api
      - GESTAO_ITENS_API_PORT=8080
      - CARRINHO_API_HOST=http://jfgr-carrinho-ecommerce-api
      - CARRINHO_API_PORT=8080
      - API_PORT=8080
      - TZ=America/Sao_Paulo
networks:
  jfgr-ecommerce:
    external: true